import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/layout/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/layout/Header";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const login = cookies().get("whistle_token")?.value;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {login ? <Header>{children}</Header> : children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
